---
  
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  myBucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://groupe-4-fil-rouge.s3.eu-west-3.amazonaws.com/create-bucket.yml

  myVpc:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://groupe-4-fil-rouge.s3.eu-west-3.amazonaws.com/create-vpc.yml
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        G4PublicSubnet1CIDR: !Ref G4PublicSubnet1CIDR

  myInstance:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://groupe-4-fil-rouge.s3.eu-west-3.amazonaws.com/create-ec2.yml
      Parameters:
        VpcId: !GetAtt myVpc.Outputs.VpcId
        SubnetId: !GetAtt myVpc.Outputs.PublicSubnet   
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType
        InstanceImageId: !Ref InstanceImageId    

Parameters:
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

  G4PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24  

  VPCStackName:
    Description: Name of the base VPC stack
    Type: String
    Default: BaseStack

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'  # standard type
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.medium

  InstanceImageId:
    Description: EC2 Image Id from this region
    Type: AWS::EC2::Image::Id
    Default: ami-06602da18c878f98d # Ubuntu image 